"""Initial Migration

Revision ID: 9b0c450be50b
Revises: 
Create Date: 2024-08-09 14:53:42.468060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b0c450be50b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if not op.get_bind().engine.dialect.has_table(conn, 'users'):
        op.create_table('users',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('status', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
        sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('last_login_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.CheckConstraint("role::text = ANY (ARRAY['ADMIN'::character varying, 'TRANSLATOR'::character varying, 'REVIEWER'::character varying]::text[])", name='users_role_check'),
        sa.CheckConstraint("status::text = ANY (ARRAY['Active'::character varying, 'Invited'::character varying]::text[])", name='users_status_check'),
        sa.PrimaryKeyConstraint('id', name='users_pkey'),
        sa.UniqueConstraint('email', name='users_email_key'),
        sa.UniqueConstraint('username', name='users_username_key')
        )
    op.execute("""
        INSERT INTO users (username, email, hashed_password, role, status, create_date, last_login_date)
        VALUES (
            'ali', 
            'alisuhaib@gmail.com', 
            '$2b$12$xondij1ww9.gyd2BRCnL8ePFtB42WURdQjuJaQARSNmgVP6Ppo1/K', 
            'ADMIN', 
            'Active', 
            NOW(), 
            NOW()
        )
    """)
    # ### end Alembic commands ###
